### ISSUE TITLE
Can you add license to you repo please?

### ISSUE THREAD

**Issue by Mnwa** [flf2ko/fasthttp-prometheus#4]
Hey! Can you add license to you repo please?

**Comment by flf2ko** [comment]
Sure. 
Just added MIT license.

**Comment by kirillDanshin** [comment]
@flf2ko actually, by [this line](https://github.com/flf2ko/fasthttp-prometheus/blob/master/LICENSE#L3) you just allowed any George in the world to revoke given license from any company 😄 can you consider changing this line so only you can control the license terms?
